'use strict';
const $=s=>document.querySelector(s);
const app=$('#app');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const state={name:'',stage:0,mapRound:0,points:{map:0,art:0,sim:0},mistakes:new Set(),placed:new Set(),archived:new Set(),selected:null,tool:'glove',solved:new Set(),log:[],rain:false,priorityMistake:false,finished:false,ignored:new Set(),avatar:{x:440,y:500},destination:null,focus:null,muted:false};
let audioContext,toastTimer,frame,lastFrame=0;
function sound(good=true){if(state.muted)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const t=audioContext.currentTime;[good?440:170,good?660:135].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=good?'sine':'triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,t+i*.1);g.gain.exponentialRampToValueAtTime(.08,t+i*.1+.01);g.gain.exponentialRampToValueAtTime(.0001,t+i*.1+.22);o.connect(g);g.connect(audioContext.destination);o.start(t+i*.1);o.stop(t+i*.1+.23);});}catch{}}
function toast(message,good=true){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);sound(good);}
function total(){return state.points.map+state.points.art+state.points.sim;}
function progress(){return Math.round((state.placed.size+state.archived.size+state.solved.size)/19*100);}
function hud(){return `<div class="hud"><div><div class="agent-name">EJEN <strong>${escapeHTML(state.name.toUpperCase())}</strong> <span aria-hidden="true"> / </span> OPERASI CODE RED</div><div class="progress-track" role="progressbar" aria-label="Kemajuan misi" aria-valuenow="${progress()}" aria-valuemin="0" aria-valuemax="100"><div class="progress-fill" style="width:${progress()}%"></div></div><div class="steps"><span class="${state.stage===1?'active':''}">01 / JEJAK TAMADUN</span><span class="${state.stage===2?'active':''}">02 / ARKIB KHAZANAH</span><span class="${state.stage===3?'active':''}">03 / OPERASI WARISAN</span></div></div><div class="score">${total()}<small> / 100</small></div></div>`;}
function refreshHud(){const old=$('.hud');if(old){old.outerHTML=hud();}}
function heading(n,title,desc,badge){return `<div class="mission-heading"><div><p class="eyebrow">${n}</p><h2>${title}</h2><p>${desc}</p></div><span class="badge">${badge}</span></div>`;}
function scrollTop(){window.scrollTo({top:0,behavior:'instant'});}
const hero=`<svg viewBox="0 0 600 620" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><pattern id="heroGrid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#647c6e" stroke-opacity=".18"/></pattern><linearGradient id="pyr" x2="1" y2="1"><stop stop-color="#f1da9b"/><stop offset="1" stop-color="#ac9161"/></linearGradient></defs><rect width="600" height="620" fill="#c6cbb0"/><rect width="600" height="620" fill="url(#heroGrid)"/><circle cx="320" cy="290" r="214" fill="none" stroke="#68857a" stroke-dasharray="4 10"/><circle cx="320" cy="290" r="165" fill="#b6bea0" stroke="#76917c"/><path d="M0 470Q170 370 300 430T600 400V620H0" fill="#a1b393"/><path d="M365 100Q250 180 400 275T355 535" fill="none" stroke="#689b97" stroke-width="36"/><path d="M365 100Q250 180 400 275T355 535" fill="none" stroke="#acd1bc" stroke-width="3" stroke-dasharray="8 12"/><path d="M70 388L230 170L360 388Z" fill="url(#pyr)"/><path d="M230 170L245 388H360Z" fill="#92774d"/><path d="M85 367H243M104 343H240M123 318H237M142 293H234M163 265H233M181 240H231" stroke="#b19360" stroke-width="2"/><path d="M343 412h205v-40H343zm25-40h155v-43H368zm27-43h101v-45H395zm27-45h48v-42h-48z" fill="#dfc17f" stroke="#927e52" stroke-width="3"/><path d="M428 410V290h33v120" fill="#8b7853"/><g transform="translate(140 420) rotate(-12)"><rect width="120" height="90" rx="15" fill="#b78660" stroke="#825d46" stroke-width="4"/><path d="M20 20l10 8-10 8m22-16 10 8-10 8m22-16 10 8-10 8M20 50l10 8-10 8m22-16 10 8-10 8m22-16 10 8-10 8" fill="none" stroke="#604d3c" stroke-width="5"/></g><g transform="translate(440 182)"><circle r="27" fill="#253e37"/><path d="M-9 0l6 7 14-16" fill="none" stroke="#f2d488" stroke-width="4"/><circle r="37" fill="none" stroke="#466754"/></g><path d="M60 80h30m-15-15v30M508 465h30m-15-15v30" stroke="#436456" stroke-width="2"/></svg>`;
function landing(){state.stage=0;app.innerHTML=`<section class="landing"><div><p class="eyebrow"><span class="dot"></span>PANGGILAN SULIT UNTUK EJEN BAHARU</p><h1>MASA LALU.<br>MISI <span class="red">KITA.</span></h1><p class="lead">Empat tamadun. Khazanah yang tidak ternilai.<br>Jejaki asal usulnya dan lindungi tinggalannya sebelum terlambat.</p><form id="start-form"><label class="name-label" for="name">Nama murid / identiti ejen</label><div class="form-row"><input id="name" name="name" placeholder="Masukkan nama anda" maxlength="40" required autocomplete="given-name"><button class="primary" type="submit">Terima misi ↗</button></div></form><p class="micro">Nama kekal dalam sesi ini sahaja. Sedia untuk bertindak?</p><div class="tags"><span>◉ PETA INTERAKTIF</span><span>◇ ARKIB ARTIFAK</span><span>⌖ SIMULASI LAPANGAN</span></div></div><div class="hero-art"><div class="hero-label">FAIL OPERASI / MH–005<br>STATUS: CODE RED</div>${hero}<div class="hero-stamp"><b>05</b><p><strong>Tamadun Awal Dunia</strong>Sejarah Tingkatan 1 · Misi berpandukan Bab 5</p></div></div></section>`;$('#start-form').onsubmit=e=>{e.preventDefault();const n=$('#name').value.trim();if(!n){$('#name').setCustomValidity('Sila masukkan nama murid.');$('#name').reportValidity();return;}state.name=n;sound();codeRedIntro();};$('#name').oninput=()=>$('#name').setCustomValidity('');}

let introTimer;
function codeRedIntro(){
  clearTimeout(introTimer);
  let remaining=10,closed=false;
  const messages=[
    ['RALAT 005 / SAMBUNGAN TERPUTUS','Isyarat asing dikesan dalam arkib tamadun.'],
    ['AMARAN / ARKIB TERANCAM','Koordinat tamadun telah dikacau. Identiti khazanah tidak dapat disahkan.'],
    ['PANGGILAN KECEMASAN','Ejen '+state.name+', pusat operasi memerlukan bantuan anda sekarang.'],
    ['LALUAN KECEMASAN DITEMUI','Memindahkan fail misi ke saluran selamat…']
  ];
  app.innerHTML='<section class="code-intro" aria-label="Pembukaan sinematik Code Red"><div class="intro-grid" aria-hidden="true"></div><div class="intro-top"><span>MH / SALURAN SULIT</span><span class="intro-live">● AMARAN AKTIF</span></div><div class="intro-content"><p class="eyebrow">TRANSMISI TERGANGGU</p><h1 class="error-title" data-text="CODE ERROR">CODE ERROR</h1><p class="intro-subtitle">ARKIB KHAZANAH DALAM BAHAYA</p><div class="countdown-box"><span>SALURAN AKAN DIKUNCI DALAM</span><strong id="intro-clock" aria-hidden="true">00:10</strong><small>KIRA DETIK OPERASI</small></div><div class="intro-terminal" role="status" aria-live="polite"><b id="intro-status"></b><p id="intro-message"></p></div><div class="intro-meter" aria-hidden="true"><i id="intro-meter-fill"></i></div><p class="intro-agent">EJEN <strong>'+escapeHTML(state.name.toUpperCase())+'</strong> · MENUNGGU ARAHAN</p></div><div class="intro-bottom"><span>SIMULASI OPERASI · FAIL MH–005</span><button id="skip-intro" class="quiet">Langkau intro →</button></div></section>';
  scrollTop();
  function finish(){if(closed)return;closed=true;clearTimeout(introTimer);sound(true);briefing();scrollTop();$('#begin').focus();}
  $('#skip-intro').onclick=finish;
  function tick(){
    if(closed||!$('#intro-clock'))return;
    $('#intro-clock').textContent='00:'+String(remaining).padStart(2,'0');
    $('#intro-meter-fill').style.width=((10-remaining)*10)+'%';
    const index=remaining>7?0:remaining>4?1:remaining>2?2:3;
    $('#intro-status').textContent=messages[index][0];
    $('#intro-message').textContent=messages[index][1];
    if(remaining===0){introTimer=setTimeout(finish,700);return;}
    sound(false);
    remaining--;
    introTimer=setTimeout(tick,1000);
  }
  tick();
}

function briefing(){app.innerHTML=`<section class="panel brief"><p class="eyebrow">IDENTITI DISAHKAN / AKSES DIBERIKAN</p><h1>Selamat datang<br><span class="red">Ejen ${escapeHTML(state.name)}</span></h1><p class="alert">RED CODE: selesaikan misi kita dan selamatkan khazanah</p><div class="mission-cards"><section><b>01 · JEJAK</b><h3>Peta tamadun</h3><p>Letakkan tamadun dan sungai pada lokasi geografi.</p></section><section><b>02 · KENAL PASTI</b><h3>Arkib khazanah</h3><p>Pulangkan setiap tinggalan kepada tamadunnya.</p></section><section><b>03 · BERTINDAK</b><h3>Selamatkan tapak</h3><p>Bergerak, siasat dan gunakan peralatan dengan bijak.</p></section></div><button id="begin" class="primary">Mulakan operasi →</button><p class="micro">Tiada had masa. Perhatikan petunjuk dan fikir sebelum bertindak.</p></section>`;$('#begin').onclick=()=>{state.stage=1;renderMap();scrollTop();};}
const mapItems=[
{id:'mesir',name:'Tamadun Mesir Purba',lon:30.8,lat:27.3,round:0,fact:'Mesir Purba berkembang di Lembah Sungai Nil.'},
{id:'meso',name:'Tamadun Mesopotamia',lon:45.3,lat:32.8,round:0,fact:'Mesopotamia ialah tanah di antara Sungai Tigris dan Euphrates.'},
{id:'indus',name:'Tamadun Indus',lon:69.1,lat:28.4,round:0,fact:'Tamadun Indus berkembang di Lembah Sungai Indus, di barat laut benua kecil India.'},
{id:'huang',name:'Tamadun Huang He',lon:114.1,lat:35.5,round:0,fact:'Tamadun Huang He berkembang di utara China.'},
{id:'nil',name:'Sungai Nil',lon:31.2,lat:25.8,round:1,fact:'Banjir Sungai Nil membawa lumpur subur untuk pertanian Mesir Purba.'},
{id:'tigris',name:'Sungai Tigris',lon:44.5,lat:33.3,round:1,fact:'Tigris ialah sungai di sebelah timur Euphrates dalam kawasan Mesopotamia.'},
{id:'euphrates',name:'Sungai Euphrates',lon:40.2,lat:35.1,round:1,fact:'Euphrates mengalir melalui kawasan Mesopotamia; Ur terletak berhampiran sungai ini.'},
{id:'sindus',name:'Sungai Indus',lon:69.2,lat:28.2,round:1,fact:'Sungai Indus menyokong petempatan dan kegiatan pertanian tamadun Indus.'},
{id:'shuang',name:'Sungai Huang He',lon:113.4,lat:34.9,round:1,fact:'Huang He dikenali sebagai Sungai Kuning kerana lumpur kekuningannya.'},
{id:'yangtze',name:'Sungai Yangtze',lon:113.8,lat:30.3,round:1,fact:'Yangtze berada di bahagian tengah China, di selatan Sungai Huang He.'}
];
let mapOrder=[],pinOrder=[],mapFeedback='Pilih label dan seret ke pin yang sepadan. Tiada jawapan diberi pada pin.';
function renderMap(){if(!mapOrder.length){mapOrder=shuffle(mapItems.filter(i=>i.round===state.mapRound));pinOrder=shuffle(mapOrder);}const round=mapItems.filter(i=>i.round===state.mapRound),done=round.every(i=>state.placed.has(i.id));app.innerHTML=hud()+heading('MISI 01 / JEJAK TAMADUN',state.mapRound?'Jejaki nadi kehidupan.':'Empat tamadun. Satu peta.',state.mapRound?'Kenal pasti enam sungai. Bezakan Tigris dengan Euphrates serta Huang He dengan Yangtze.':'Seret nama tamadun ke pin lokasinya. Perhatikan benua, pantai dan lembah sungai.',`PUSINGAN ${state.mapRound+1} / 2`)+`<div class="map-layout"><section class="map-card"><div class="map-toolbar"><strong>ATLAS LAPANGAN / AFRIKA–ASIA</strong><button id="zoom">＋ Zum peta</button></div><div class="map-scroll"><div class="map-world"><img src="assets/world-map.svg" alt="Peta geografi Afrika timur laut hingga Asia timur dengan garis pantai, sempadan moden dan enam sungai ditanda biru" draggable="false">${pinOrder.map((i,n)=>`<button class="pin ${state.placed.has(i.id)?'done':''}" data-pin="${i.id}" style="left:${(i.lon-15)*.9}%;top:${(57-i.lat)*10/5.2}%" aria-label="Pin ${n+1}${state.placed.has(i.id)?': '+i.name:''}">${state.placed.has(i.id)?'✓':n+1}<span class="pin-label">${i.name}</span></button>`).join('')}</div></div><div class="map-caption">Biru: aliran sungai · Utara ↑ · Pin menandakan kawasan rujukan, bukan keseluruhan wilayah tamadun. Leret peta / zum untuk lokasi berdekatan.</div></section><aside class="panel label-bank"><p class="eyebrow">BEKALAN INTEL</p><h3>${round.filter(i=>!state.placed.has(i.id)).length} label belum diletakkan</h3><p>Seret label, atau ketik label kemudian pin. Label diacak setiap sesi.</p><div class="labels">${mapOrder.map(i=>`<button class="drag-label ${state.placed.has(i.id)?'done':''}" data-label="${i.id}" ${state.placed.has(i.id)?'disabled':''}>${state.placed.has(i.id)?'✓':'⠿'} ${i.name}</button>`).join('')}</div></aside></div><div class="feedback" role="status">${escapeHTML(mapFeedback)}</div><div class="next-row"><button class="primary" id="map-next" ${done?'':'disabled'}>${state.mapRound?'Buka arkib khazanah':'Teruskan: jejaki sungai'} →</button></div>`;
$('#zoom').onclick=()=>{const z=$('.map-world').classList.toggle('zoomed');$('#zoom').textContent=z?'− Kecilkan':'＋ Zum peta';};
document.querySelectorAll('[data-label]').forEach(el=>{el.onclick=()=>selectLabel(el.dataset.label);el.onpointerdown=e=>startDrag(e,el);});
document.querySelectorAll('[data-pin]').forEach(el=>el.onclick=()=>placeLabel(state.selected,el.dataset.pin));
$('#map-next').onclick=()=>{if(!done)return;state.selected=null;if(!state.mapRound){state.mapRound=1;mapOrder=[];mapFeedback='Perhatikan sungai di timur dan barat. Gunakan zum jika dua pin berdekatan.';renderMap();}else{state.stage=2;renderArtifacts();}scrollTop();};}
function selectLabel(id){if(state.placed.has(id))return;state.selected=id;document.querySelectorAll('[data-label]').forEach(e=>e.classList.toggle('selected',e.dataset.label===id));}
function placeLabel(id,pin){if(!id){toast('Pilih satu label terlebih dahulu.',false);return;}if(state.placed.has(id))return;if(id!==pin){state.mistakes.add(id);$('.feedback').textContent='Lokasi belum tepat. Perhatikan kedudukan sungai, pantai dan benua; cuba semula. Nilai label ini kini 2/3 markah.';toast('Semak lokasi dan cuba semula.',false);return;}state.placed.add(id);state.points.map+=state.mistakes.has(id)?2:3;state.selected=null;mapFeedback=mapItems.find(i=>i.id===id).fact;toast('Lokasi disahkan. Intel berjaya dipulihkan.');renderMap();}
function startDrag(e,el){if(e.button!==0||state.placed.has(el.dataset.label))return;selectLabel(el.dataset.label);let moved=false,ghost;const sx=e.clientX,sy=e.clientY;el.setPointerCapture(e.pointerId);const move=ev=>{if(Math.hypot(ev.clientX-sx,ev.clientY-sy)>7)moved=true;if(!moved)return;if(!ghost){ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=el.textContent;document.body.appendChild(ghost);}ghost.style.left=(ev.clientX+8)+'px';ghost.style.top=(ev.clientY-50)+'px';};const end=ev=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',cancel);ghost?.remove();if(moved){const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('[data-pin]');if(target)placeLabel(el.dataset.label,target.dataset.pin);else toast('Lepaskan label pada pin bulat di peta.',false);}};const cancel=()=>{ghost?.remove();el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',cancel);};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',cancel);}
function artSVG(type){const start='<svg viewBox="0 0 240 190" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="120" cy="159" rx="82" ry="13" fill="#968f7040"/>';const drawings={tablet:'<g transform="rotate(-9 120 95)"><rect x="53" y="31" width="138" height="126" rx="20" fill="#b88963" stroke="#825f49" stroke-width="4"/><rect x="64" y="42" width="116" height="102" rx="12" fill="#c29970"/><g stroke="#715643" stroke-width="4" fill="none"><path d="M78 58l12 7-12 7m27-14 12 7-12 7m27-14 12 7-12 7m27-14 8 7-8 7M78 87l12 7-12 7m27-14 12 7-12 7m27-14 12 7-12 7M78 116l12 7-12 7m27-14 12 7-12 7m27-14 12 7-12 7m27-14 8 7-8 7"/></g></g>',pyramid:'<path d="M30 153L120 28L212 153Z" fill="#d6b16a"/><path d="M120 28L133 153H212Z" fill="#9b784c"/><path d="M44 134h87M58 114h71M73 93h54M86 73h39M100 53h23" stroke="#aa8954" stroke-width="2"/><rect x="139" y="130" width="13" height="23" fill="#665b45"/>',city:'<path d="M32 65L131 23L219 73L123 134Z" fill="#c8b18b"/><g fill="#ae8c66" stroke="#776b4f" stroke-width="2"><path d="M41 70V52l25-12 21 12v18L63 83Z"/><path d="M95 45V28l25-10 21 12v18l-25 12Z"/><path d="M151 67V49l25-11 22 13v18l-25 12Z"/><path d="M46 124v-18l25-12 22 13v18l-25 12Z"/><path d="M152 125v-18l25-12 22 13v18l-25 12Z"/></g><path d="M93 78l30-15 29 16-29 17Z" fill="#497f7d" stroke="#ebe3c6" stroke-width="6"/><path d="M33 90l91 51 88-46M122 151v18M90 63l76 44" fill="none" stroke="#eee5c8" stroke-width="6"/><path d="M122 143v25" stroke="#548e8c" stroke-width="3"/>',silk:'<path d="M70 43Q123 17 178 43v103Q125 124 70 150Z" fill="#a75447" stroke="#744b3e" stroke-width="3"/><ellipse cx="70" cy="97" rx="16" ry="55" fill="#dbc19a"/><ellipse cx="70" cy="97" rx="7" ry="43" fill="#ad9473"/><path d="M105 43v98m30-103v97m29-95v102" stroke="#eac580" stroke-width="3"/><path d="M90 60q40-12 88 0M89 85q40-12 89 0M88 110q40-12 90 0" stroke="#eac580" stroke-width="3"/><path d="M111 68l12 14-12 14-12-14Z" fill="#e7ca8d"/>'};return start+drawings[type]+'</svg>';}
const artifacts=[{id:'tablet',name:'Tablet kuneiform',civ:'Mesopotamia',desc:'Tanda berbentuk baji pada tablet tanah liat.',fact:'Tulisan kuneiform ialah sumbangan Tamadun Mesopotamia (hlm. 106).'}, {id:'pyramid',name:'Model piramid',civ:'Mesir Purba',desc:'Binaan monumental sebagai makam raja.',fact:'Piramid dibina sebagai kawasan perkuburan raja Mesir (hlm. 106).'}, {id:'city',name:'Model kota bergrid',civ:'Indus',desc:'Jalan tersusun dan sistem pembetungan.',fact:'Kota Tamadun Indus mempunyai susunan grid dan sistem pembetungan (hlm. 105, 107).'}, {id:'silk',name:'Gulungan sutera',civ:'Huang He',desc:'Hasil kemahiran menghasilkan kain sutera.',fact:'Penghasilan sutera disenaraikan sebagai sumbangan Tamadun Huang He (hlm. 105).'}];
let artOrder=shuffle(artifacts),civOrder=shuffle(['Mesopotamia','Mesir Purba','Indus','Huang He']),artFeedback='Pilih satu objek bergambar, kemudian pilih ruang arkib tamadunnya.';
function renderArtifacts(){app.innerHTML=hud()+heading('MISI 02 / ARKIB KHAZANAH','Pulangkan kisah di sebalik objek.','Periksa tinggalan, model dan hasil cipta. Kenal pasti tamadun berdasarkan ciri visual serta keterangannya.',`${state.archived.size} / 4 DIARKIBKAN`)+`<div class="artifact-grid">${artOrder.map((a,i)=>`<button class="artifact ${state.archived.has(a.id)?'done':''} ${state.selected===a.id?'selected':''}" data-art="${a.id}" ${state.archived.has(a.id)?'disabled':''}><span class="art-image">${artSVG(a.id)}</span><span class="art-info"><small>OBJEK ${String(i+1).padStart(2,'0')} / ILUSTRASI</small><strong>${a.name}</strong><span class="micro">${a.desc}</span></span></button>`).join('')}</div><section class="panel archive-panel"><p class="eyebrow">RUANG ARKIB</p><h3 id="art-selection">${state.selected?'Objek dipilih: '+artifacts.find(a=>a.id===state.selected).name:'Pilih objek untuk diperiksa'}</h3><div class="destinations">${civOrder.map(c=>`<button data-civ="${c}" ${state.selected?'':'disabled'}>◇ ${c}</button>`).join('')}</div></section><div class="feedback" role="status">${escapeHTML(artFeedback)}</div><div class="next-row"><button id="art-next" class="primary" ${state.archived.size===4?'':'disabled'}>Masuk ke tapak warisan →</button></div>`;document.querySelectorAll('[data-art]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.art;renderArtifacts();});document.querySelectorAll('[data-civ]').forEach(el=>el.onclick=()=>archive(el.dataset.civ));$('#art-next').onclick=()=>{if(state.archived.size!==4)return;state.selected=null;state.stage=3;renderSimulation();scrollTop();};}
function archive(civ){const a=artifacts.find(a=>a.id===state.selected);if(!a||state.archived.has(a.id))return;if(a.civ!==civ){state.mistakes.add(a.id);artFeedback='Perhatikan ciri objek: '+a.desc+' Cuba ruang arkib lain. Nilai objek ini kini 3/5 markah.';toast('Arkib belum sepadan.',false);renderArtifacts();return;}state.archived.add(a.id);state.points.art+=state.mistakes.has(a.id)?3:5;artFeedback=a.fact;state.selected=null;toast('Objek berjaya diarkibkan.');renderArtifacts();}
const toolsList=[['glove','🧤','Sarung tangan'],['radio','◉','Radio'],['cover','⛺','Kanopi'],['barrier','🚧','Penghadang'],['drain','♧','Penyodok'],['brush','🖌','Berus']];
const objects={trash:{x:180,y:425,title:'Sampah di laluan',detail:'Botol dan kertas berselerak di laluan pelawat. Bersihkan tanpa mengganggu struktur purba.',tool:'glove',points:8,success:'Sampah dikutip dengan sarung tangan. Laluan kembali bersih.',reason:'Kebersihan mengurangkan pencemaran dan risiko kepada pelawat.'},vandal:{x:690,y:235,title:'Vandalisme di tembok',detail:'Seorang pelawat sedang menconteng. Kekalkan jarak selamat. Cat lama memerlukan rawatan pakar.',tool:'radio',points:10,success:'Pengawal menerima laporan. Pelawat dihentikan dan zon rawatan ditandakan.',reason:'Melapor melindungi keselamatan ejen dan mengelakkan kerosakan lanjut.'},relic:{x:365,y:285,title:'Artifak terdedah',detail:'Serpihan tembikar baru ditemui. Kedudukan asal ialah bukti penting. Lindungi di tempat asal tanpa menyentuhnya.',tool:'cover',points:12,success:'Kanopi dipasang tanpa menyentuh artifak. Lokasi dihantar kepada pegawai konservasi.',reason:'Perlindungan di tempat asal mengekalkan konteks penemuan.'},gate:{x:710,y:440,title:'Pelawat menghampiri zon licin',detail:'HUJAN: orang ramai masih menghampiri kawasan licin di tepi ekskavasi. Utamakan keselamatan mereka sebelum kerja saliran.',tool:'barrier',points:10,success:'Penghadang dipasang. Pelawat dialih ke laluan selamat.',reason:'Menghalang akses ke zon berbahaya mengutamakan nyawa dan keselamatan.'},drain:{x:155,y:215,title:'Saliran moden tersumbat',detail:'HUJAN: daun menyekat saliran moden di luar struktur purba. Air naik ke arah ekskavasi. Pastikan pelawat selamat sebelum membuka aliran.',tool:'drain',points:10,success:'Daun dialihkan dari saliran moden. Air mengalir keluar dan tapak terselamat.',reason:'Menyelesaikan punca air bertakung melindungi tapak tanpa mengubah tinggalan purba.'}};
let contextMessage='Sentuh objek untuk menghampirinya. Ejen akan berjalan ke lokasi yang selamat.';
function objectMarkup(id,body,label){const o=objects[id],done=state.solved.has(id);return `<g class="world-object" data-object="${id}" transform="translate(${o.x} ${o.y})" tabindex="0" role="button" aria-label="${o.title}${done?' — selesai':''}"><circle r="49" fill="${done?'#9fe1b526':'#fff1bd20'}" stroke="${done?'#4a8063':'#eed08e'}" stroke-width="2" stroke-dasharray="5 6"/>${body}<rect x="-82" y="48" width="164" height="25" rx="7" fill="#203d35"/><text x="0" y="65" text-anchor="middle" font-size="12" fill="#fff2cb">${done?'✓ ':''}${label}</text></g>`;}
function sceneSVG(){const solved=id=>state.solved.has(id);return `<svg class="scene" id="scene" viewBox="0 0 900 600" role="group" aria-label="Tapak warisan interaktif; pilih objek untuk menggerakkan ejen"><defs><pattern id="grass" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M8 20l3-6 3 6M34 44l3-6 3 6" fill="none" stroke="#718e6045"/></pattern><pattern id="brick" width="45" height="24" patternUnits="userSpaceOnUse"><rect width="45" height="24" fill="#b7a47a"/><path d="M0 0h45v24H0Zm23 0v24" fill="none" stroke="#8a7e61"/></pattern></defs><rect width="900" height="600" fill="${state.rain?'#9bad95':'#b4c29b'}"/><rect width="900" height="600" fill="url(#grass)"/><path d="M-20 470Q180 345 370 415T930 435" stroke="#d9cbb0" stroke-width="105" fill="none"/><path d="M442 650V70" stroke="#d9cbb0" stroke-width="80" fill="none"/><path d="M90 0Q120 120 90 240T80 610" stroke="#749c91" stroke-width="35" fill="none"/><path d="M90 0Q120 120 90 240T80 610" stroke="#bbd6b4" stroke-width="3" stroke-dasharray="12 20" fill="none"/><rect x="260" y="152" width="270" height="197" rx="8" fill="#8f8763"/><rect x="274" y="165" width="242" height="169" fill="#c5b38b"/><path d="M280 210h230M280 270h230M330 164v170M405 164v170M473 164v170" stroke="#ada17b" stroke-width="2"/><path d="M270 337V152h260v185" fill="none" stroke="url(#brick)" stroke-width="22"/><path d="M580 138h185v84H580Z" fill="url(#brick)" stroke="#807554" stroke-width="4"/><path d="M580 138l15-14h185l-15 14" fill="#d4c59d"/><g fill="#587854"><circle cx="820" cy="105" r="36"/><circle cx="795" cy="88" r="29"/><circle cx="835" cy="75" r="24"/><circle cx="245" cy="84" r="32"/><circle cx="220" cy="64" r="25"/><circle cx="570" cy="520" r="28"/><circle cx="605" cy="522" r="31"/></g><g stroke="#765e44" stroke-width="10"><path d="M820 111v44M240 83v37M590 532v35"/></g><rect x="770" y="515" width="75" height="32" rx="4" fill="#556e53"/><text x="808" y="536" fill="#e7edce" text-anchor="middle" font-size="11">PINTU MASUK</text>
${state.rain?`<path d="M95 220Q200 170 285 234L284 345Q190 340 110 285Z" fill="#74a7b5" opacity="${solved('drain')?'.12':'.7'}"/>`:''}
${objectMarkup('trash',solved('trash')?'<path d="M-18 0l12 12 27-29" fill="none" stroke="#3c7254" stroke-width="7"/>':'<g transform="rotate(25)"><rect x="-28" y="-9" width="16" height="35" rx="4" fill="#d7eae3" stroke="#527d77" stroke-width="3"/><path d="M-25-14h10v6h-10" fill="#46698c"/></g><path d="M3-10l28 6-8 27L0 18Z" fill="#efebd2"/><path d="M17-31l10 2-2 13-10-2Z" fill="#b77e5c"/>','LALUAN')}
${objectMarkup('vandal',`<path d="M-59-42l28 20-19 14 41 10" stroke="#9e4754" stroke-width="7" fill="none"/>${solved('vandal')?'<path d="M-45 5h90M-35 5v32M35 5v32" stroke="#eac263" stroke-width="7"/><rect x="-34" y="-16" width="68" height="24" rx="3" fill="#294637"/><text text-anchor="middle" y="0" font-size="10" fill="#f7da8a">RAWATAN</text>':'<circle cx="28" cy="-12" r="13" fill="#be926b"/><path d="M28 0v28m0-18-26-18m26 35-13 20m13-20 12 20" stroke="#684d58" stroke-width="11" stroke-linecap="round"/><path d="M0-8l-7-5" stroke="#d17e72" stroke-width="6"/>'}`,'TEMBOK')}
${objectMarkup('relic',`<path d="M-18-5q-8 33 5 37h22q15-7 8-37l-7-6H-10Z" fill="#b87a51" stroke="#76563d" stroke-width="3"/><path d="M-15 11h30m-31 9h32" stroke="#e9bb7f" stroke-width="3"/>${solved('relic')?'<path d="M-40 0v43M40 0v43" stroke="#756347" stroke-width="4"/><path d="M-53 0L0-37 53 0Z" fill="#e9d29d" stroke="#8c7751" stroke-width="3"/><path d="M-40 36h80" stroke="#dbc676" stroke-width="3"/>':''}`,'EKSKAVASI')}
${state.rain?objectMarkup('gate',solved('gate')?'<path d="M-48 0h96M-38 0v34M38 0v34" stroke="#e9c35f" stroke-width="9"/><path d="M-40-3l13 7m12-7 13 7m12-7 13 7m12-7 13 7" stroke="#425448" stroke-width="5"/>':'<g fill="#435d69"><circle cx="-19" cy="-13" r="12"/><rect x="-30" y="0" width="22" height="30" rx="6"/><circle cx="18" cy="-5" r="10"/><rect x="9" y="6" width="18" height="26" rx="6"/></g>','AKSES PELAWAT'):''}
${state.rain?objectMarkup('drain',`<rect x="-30" y="-22" width="60" height="50" fill="#4f6460" stroke="#b8b797" stroke-width="5"/><path d="M-22-15v34M-11-15v34M0-15v34M11-15v34M22-15v34" stroke="#aab6a6" stroke-width="4"/>${solved('drain')?'<path d="M-48 0h-24m10-8-10 8 10 8" fill="none" stroke="#d0f0ec" stroke-width="5"/>':'<g fill="#a3784c"><ellipse cx="-15" cy="-4" rx="17" ry="7" transform="rotate(30)"/><ellipse cx="15" cy="12" rx="17" ry="8" transform="rotate(-20)"/><ellipse cx="5" cy="-10" rx="13" ry="8"/></g>'}`,'SALIRAN MODEN'):''}
<g id="avatar" transform="translate(${state.avatar.x} ${state.avatar.y})" pointer-events="none"><ellipse cy="23" rx="18" ry="8" fill="#34443555"/><circle r="34" fill="none" stroke="#fff7cf" stroke-width="2" stroke-dasharray="4 7"/><path d="M-8 12v14M8 12v14" stroke="#253b38" stroke-width="7" stroke-linecap="round"/><rect x="-14" y="-9" width="28" height="29" rx="9" fill="#ee7257" stroke="#593f32" stroke-width="2"/><circle cy="-17" r="13" fill="#d3ad80"/><path d="M-15-20q14-21 30 0" fill="#27443b"/><rect x="-12" y="-21" width="24" height="7" rx="2" fill="#324f48"/><path d="M-4 1h8v8h-8" fill="#f5d688"/><text x="0" y="-43" text-anchor="middle" fill="#213e36" font-size="11" font-weight="bold">EJEN</text></g>
${state.rain&&!solved('drain')?`<g class="rain-layer">${Array.from({length:35},(_,i)=>`<path class="rain-line" d="M${(i*139)%900} ${(i*71)%520}l-8 24" style="animation-delay:-${i*.08}s"/>`).join('')}</g>`:''}</svg>`;}
function renderSimulation(){cancelAnimationFrame(frame);app.innerHTML=hud()+heading(state.rain?'CABARAN AKHIR / KBAT DALAM TINDAKAN':'MISI 03 / OPERASI WARISAN',state.rain?'Hujan tiba. Tentukan keutamaan.':'Khazanah ini dalam jagaan anda.',state.rain?'Pelawat menghampiri zon licin, air pula naik ke arah ekskavasi. Bertindak berdasarkan risiko; urutan tindakan anda direkodkan.':'Teroka tapak, dekati objek dan gunakan alat yang sesuai. Setiap keputusan meninggalkan kesan pada kawasan.',state.rain?'AMARAN CUACA':'SIMULASI LAPANGAN')+`<div class="sim-layout"><div class="scene-wrap">${sceneSVG()}<div class="scene-status">${state.rain?'☂ HUJAN / TINDAKAN SEGERA':'⌖ TAPAK LATIHAN / AKSES EJEN'}</div><div class="scene-tip">Sentuh tanah / objek untuk bergerak · Anak panah / WASD untuk berjalan</div></div><aside class="panel sim-panel"><p class="eyebrow">PERALATAN EJEN</p><div class="tool-grid">${toolsList.map(([id,icon,name])=>`<button class="tool ${state.tool===id?'selected':''}" data-tool="${id}" aria-pressed="${state.tool===id}"><span aria-hidden="true">${icon}</span>${name}</button>`).join('')}</div><div id="object-context"></div><button class="primary full" id="use-tool" disabled>Gunakan alat</button><button class="quiet full" id="report-vandal" hidden>Tegur dari jarak selamat</button><button class="quiet full" id="ignore" disabled>Abaikan & terus berjalan</button><div class="log"><strong>RADIO OPERASI</strong><p id="radio-message" role="status">${escapeHTML(contextMessage)}</p></div></aside></div><div class="next-row"><button class="gold" id="finish" ${state.solved.size===5?'':'disabled'}>Tamatkan operasi & lihat laporan →</button></div>`;document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(e=>{e.classList.toggle('selected',e.dataset.tool===state.tool);e.setAttribute('aria-pressed',e.dataset.tool===state.tool);});updateContext();});$('#scene').onclick=sceneClick;document.querySelectorAll('[data-object]').forEach(g=>g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();approach(g.dataset.object);}});$('#use-tool').onclick=applyTool;$('#ignore').onclick=ignoreObject;$('#report-vandal').onclick=warnVandal;$('#finish').onclick=()=>{if(state.solved.size===5){state.finished=true;renderSummary();scrollTop();}};updateContext();lastFrame=0;frame=requestAnimationFrame(animate);}
function scenePoint(e){const svg=$('#scene'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function sceneClick(e){const object=e.target.closest('[data-object]');if(object){approach(object.dataset.object);return;}const p=scenePoint(e);state.focus=null;state.destination={x:Math.max(115,Math.min(840,p.x)),y:Math.max(95,Math.min(550,p.y))};updateContext();}
function approach(id){state.focus=id;const o=objects[id];state.destination={x:o.x,y:o.y+83};updateContext();}
function isNear(){const o=objects[state.focus];return o&&Math.hypot(state.avatar.x-o.x,state.avatar.y-o.y)<=95;}
function updateContext(){const box=$('#object-context');if(!box)return;const o=objects[state.focus],done=state.solved.has(state.focus),near=isNear();box.innerHTML=o?`<h3 class="object-title">${o.title}</h3><p>${done?'Kawasan ini sudah dilindungi. Teruskan rondaan.':o.detail}</p><div class="near-indicator">${done?'✓ Tindakan selesai':near?'● Dalam jarak tindakan':'◌ Bergerak menghampiri objek…'}</div>`:'<h3 class="object-title">Perhatikan sekeliling.</h3><p>Pilih objek di tapak untuk menyiasat. Alat hanya boleh digunakan apabila ejen berada dekat.</p><div class="near-indicator">⌖ Sedia menerima arahan</div>';$('#use-tool').disabled=!o||!near||done;$('#use-tool').textContent='Gunakan '+toolsList.find(t=>t[0]===state.tool)[2];$('#ignore').disabled=!o||!near||done;$('#report-vandal').hidden=state.focus!=='vandal'||done;$('#report-vandal').disabled=!near;}
function animate(time){if(state.stage!==3||state.finished)return;const dt=lastFrame?Math.min((time-lastFrame)/1000,.05):0;lastFrame=time;const d=state.destination;if(d){const dx=d.x-state.avatar.x,dy=d.y-state.avatar.y,dist=Math.hypot(dx,dy),step=200*dt;if(dist<=step){state.avatar={...d};state.destination=null;updateContext();}else{state.avatar.x+=dx/dist*step;state.avatar.y+=dy/dist*step;}$('#avatar')?.setAttribute('transform',`translate(${state.avatar.x} ${state.avatar.y})`);const use=$('#use-tool');if(use&&use.disabled&&isNear()&&!state.solved.has(state.focus))updateContext();}frame=requestAnimationFrame(animate);}
document.addEventListener('keydown',e=>{if(state.stage!==3||state.finished||$('#help').open||/INPUT|TEXTAREA|BUTTON/.test(e.target.tagName))return;const deltas={ArrowUp:[0,-25],w:[0,-25],ArrowDown:[0,25],s:[0,25],ArrowLeft:[-25,0],a:[-25,0],ArrowRight:[25,0],d:[25,0]};const move=deltas[e.key];if(!move)return;e.preventDefault();state.destination=null;state.avatar.x=Math.max(115,Math.min(840,state.avatar.x+move[0]));state.avatar.y=Math.max(95,Math.min(550,state.avatar.y+move[1]));$('#avatar')?.setAttribute('transform',`translate(${state.avatar.x} ${state.avatar.y})`);const nearest=Object.keys(objects).filter(id=>state.rain||!['gate','drain'].includes(id)).sort((a,b)=>Math.hypot(state.avatar.x-objects[a].x,state.avatar.y-objects[a].y)-Math.hypot(state.avatar.x-objects[b].x,state.avatar.y-objects[b].y))[0];state.focus=Math.hypot(state.avatar.x-objects[nearest].x,state.avatar.y-objects[nearest].y)<95?nearest:null;updateContext();});
function logAction(text,result){state.log.push({step:state.log.length+1,object:objects[state.focus]?.title||'Tapak',action:text,result});}
function wrong(message){const id=state.focus;if(!state.mistakes.has('sim-'+id)){state.mistakes.add('sim-'+id);logAction(toolsList.find(t=>t[0]===state.tool)[2],'Perlu dibaiki: '+message);}contextMessage=message+' Cuba tindakan lain; nilai tugasan ini berkurang 3 markah sekali sahaja.';$('#radio-message').textContent=contextMessage;toast(message,false);}
function applyTool(){const id=state.focus,o=objects[id];if(!o||!isNear()||state.solved.has(id))return;if(state.tool!==o.tool){if(state.tool==='radio'&&id==='relic'){logAction('Lapor penemuan','Lokasi direkod; perlindungan fizikal masih diperlukan.');contextMessage='Lokasi diterima. Pasang kanopi tanpa menyentuh artifak sementara menunggu pakar.';$('#radio-message').textContent=contextMessage;toast('Laporan diterima. Lindungi artifak di tempat asal.');return;}if(state.tool==='radio'&&['gate','drain'].includes(id)){contextMessage='Bantuan sedang dalam perjalanan. Gunakan penghadang untuk pelawat dan alihkan daun dari saliran moden apabila kawasan selamat.';$('#radio-message').textContent=contextMessage;toast('Pusat operasi memberi arahan keselamatan.');return;}const msg=id==='vandal'?'Jangan sental cat pada batu purba sendiri. Laporkan kepada pengawal.':id==='relic'?'Jangan alih atau bersihkan penemuan. Kekalkan konteks asalnya.':id==='gate'?'Pelawat memerlukan penghadang fizikal di zon licin.':id==='drain'?'Alihkan daun di saliran moden dengan alat yang sesuai.':'Gunakan sarung tangan untuk mengutip sampah dengan selamat.';wrong(msg);return;}if(id==='drain'&&!state.solved.has('gate')){state.priorityMistake=true;wrong('Pelawat masih terdedah kepada bahaya. Selamatkan akses mereka dahulu.');return;}state.solved.add(id);state.points.sim+=Math.max(0,o.points-(state.mistakes.has('sim-'+id)?3:0)-(state.ignored.has(id)?2:0));logAction('Gunakan '+toolsList.find(t=>t[0]===state.tool)[2],o.success);contextMessage=o.success;toast(o.success);if(!state.rain&&['trash','vandal','relic'].every(k=>state.solved.has(k))){state.rain=true;state.focus=null;contextMessage='AMARAN: hujan lebat! Pelawat menghampiri zon licin dan saliran tersumbat. Nilai risiko sebelum memilih tindakan.';logAction('Amaran cuaca diterima','Cabaran KBAT bermula.');}renderSimulation();}
function warnVandal(){if(state.focus!=='vandal'||!isNear()||state.solved.has('vandal'))return;contextMessage='Anda menegur dengan sopan dari jarak selamat. Pelawat berhenti seketika; hubungi pengawal untuk tindakan lanjut.';logAction('Tegur dari jarak selamat','Konflik dielakkan; laporan kepada pengawal masih diperlukan.');$('#radio-message').textContent=contextMessage;toast('Teguran selamat dibuat. Hubungi pengawal.');}
function ignoreObject(){const id=state.focus;if(!id||!isNear()||state.solved.has(id))return;if(!state.ignored.has(id)){state.ignored.add(id);logAction('Abaikan','Risiko kekal di tapak; 2 markah tugasan ditolak.');}contextMessage='Objek dibiarkan. Risikonya masih ada; anda boleh kembali dan membetulkan tindakan. Potongan 2 markah hanya sekali bagi objek ini.';state.focus=null;state.destination={x:440,y:500};$('#radio-message').textContent=contextMessage;updateContext();toast('Risiko belum diselesaikan.',false);}
function rating(){return total()>=90?'Ejen Khazanah Cemerlang':total()>=75?'Ejen Khazanah Berjaya':'Ejen Khazanah Dalam Latihan';}
function renderSummary(){cancelAnimationFrame(frame);app.innerHTML=`<section class="summary panel"><div class="result-top"><div class="score-disc"><strong>${total()}</strong><span>DARIPADA 100</span></div><div><p class="eyebrow">OPERASI SELESAI / KHAZANAH SELAMAT</p><h2>Syabas, Ejen ${escapeHTML(state.name)}.</h2><p>${rating()}. Semua lokasi dikenal pasti dan kawasan tapak telah dilindungi.</p></div></div><div class="stats"><div><b>${state.points.map} / 30</b><span>Jejak tamadun & sungai</span></div><div><b>${state.points.art} / 20</b><span>Arkib khazanah</span></div><div><b>${state.points.sim} / 50</b><span>Tindakan pemuliharaan</span></div></div><h3>Penilaian KBAT: bukti daripada tindakan</h3><p>${state.priorityMistake?'Anda cuba mengurus saliran sebelum akses pelawat selamat, kemudian membetulkan keutamaan.':'Anda melindungi pelawat sebelum membuka saliran yang tersumbat.'} ${state.ignored.size?'Ada risiko yang pernah diabaikan; anda kembali menyelesaikannya.':'Semua risiko ditangani tanpa memilih untuk mengabaikannya.'}</p><table class="report-table"><thead><tr><th>Tindakan dinilai</th><th>Mengapa tindakan ini penting</th></tr></thead><tbody>${Object.values(objects).map(o=>`<tr><td>${o.title}</td><td>${o.reason}</td></tr>`).join('')}</tbody></table><details class="log"><summary>Lihat rekod tindakan (${state.log.length})</summary>${state.log.map(l=>`<p><strong>${l.step}. ${escapeHTML(l.object)} — ${escapeHTML(l.action)}</strong><br>${escapeHTML(l.result)}</p>`).join('')}</details><div class="next-row"><button id="download-report" class="gold">Muat turun laporan</button><button id="replay" class="quiet">Main semula · sesi baharu</button></div><p class="micro">Misi peta dan arkib menilai fakta Bab 5. Simulasi menilai aplikasi nilai pemuliharaan. Laporan ini ialah maklum balas pembelajaran.</p></section>`;$('#download-report').onclick=downloadReport;$('#replay').onclick=()=>location.reload();}
function downloadReport(){const report=`MISSION HISTORY: CODE RED\nNama ejen: ${state.name}\nKeputusan: ${rating()}\nMarkah: ${total()}/100\nPeta: ${state.points.map}/30 | Arkib: ${state.points.art}/20 | Simulasi: ${state.points.sim}/50\n\nREKOD TINDAKAN\n${state.log.map(l=>`${l.step}. ${l.object}\n   ${l.action}\n   ${l.result}`).join('\n')}\n\nPENILAIAN KBAT\n${state.priorityMistake?'Keutamaan keselamatan dibetulkan selepas maklum balas.':'Keselamatan pelawat diutamakan sebelum pengurusan saliran.'}\nRisiko pernah diabaikan: ${state.ignored.size}\n\nRujukan fakta: Buku Teks Sejarah Tingkatan 1, Bab 5, hlm. 92–107.\nSimulasi ialah situasi rekaan untuk aplikasi nilai pemuliharaan.\n`;const url=URL.createObjectURL(new Blob(['\ufeff'+report],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='laporan-mission-history.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#sound').onclick=()=>{state.muted=!state.muted;$('#sound').textContent=state.muted?'♫ Bunyi OFF':'♫ Bunyi ON';$('#sound').setAttribute('aria-pressed',!state.muted);if(!state.muted)sound();};$('#sources').onclick=()=>$('#help').showModal();$('#close-help').onclick=()=>$('#help').close();
landing();

